language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- python setup.py -q install
script:
  -
deploy:
  provider: pypi
  skip_existing: true
  user: kbyte
  distributions: sdist bdist_wheel
  password:
    secure: HF6O+bOS29MsOAgF04kPa1HrJb2DY9fzsLjxfCiI6Kik+dCsuMPiEvr1IeniJEIN5psyxIlnARppcawP+qor0pVy37QhSasXCQU7M8KtRH8gQgiV4LfL1e8AYiQalXj3cfCZnjGCpbwjqhZbZHZ2VWjGu73jfsyOyb4iE4xtCPjPVqdWxvI01KEdde/pZoX5ELH6gBhXFdxfY+FWXuO3H0fNKf+GFr7X3G6fwreVLnKbmNmgEZ2R+i843OHzByOTX2uV7E/eQziXbclBzH1blHFj74/xyrUjv1BX3qxfwplnA1DvvoMCy39eEkU4FeF+Xa6F/RMNj+t3oVHvBzxryZxe5Ll1zwpE1j0Z6q6qCSwFeIqtCT9/rjnO5y+EBlsyVSu7bqQ7plh1iTQLv6kgBCsgE0pgQo9r91EjrUFhxejnZOgnJdNWy2Ub1hbC2Ic0kAfyULp11VimeT2udWeRNBZ8qNjo6lGjJKdc4Vh7yirA2ogAYvalWgr2OZe7/U5vwvNByWyoqyhdCdRBeC8ZDCGA59inj8DfdIFQuJVaz9c6Wng68xJLbp2S7vIqvxOs28BjUyPItSAWdO6bxxk1ADXkHDBcqawOVKUS5VJ+g+n6DFpoPQiX8HjnRNVYJ1St+P3k45bxOQB1Nc7NdwP0FDtw7PxvgS0/kNpu5BuPPdE=
  on:
    tags: true
    python: '3.6'
